import { IOption } from "@/common/components/interfaces";

export const SPEECH_TO_TEXT_LANGUAGE_LIST: IOption[] = [
  {
    label: "Afrikaans",
    value: "af" 
  },
  {
    label: "Arabic",
    value: "ar" 
  },
  {
    label: "Armenian",
    value: "hy" 
  },

  // "Arabic",
  // "Armenian",
  // "Azerbaijani",
  // "Belarusian",
  // "Bosnian",
  // "Bulgarian",
  // "Catalan",
  // "Chinese (简笔)",
  // "Chinese (繁体)",
  // "Croatian",
  // "Czech",
  // "Danish",
  // "Dutch",
  // "English",
  // "Estonian",
  // "Finnish",
  // "French",
  // "Galician",
  // "German",
  // "Greek",
  // "Hebrew",
  // "Hindi",
  // "Hungarian",
  // "Icelandic",
  // "Indonesian",
  // "Italian",
  // "Japanese (日文)",
  // "Kannada",
  // "Kazakh",
  // "Korean",
  // "Latvian",
  // "Lithuanian",
  // "Macedonian",
  // "Malay",
  // "Marathi",
  // "Maori",
  // "Nepali",
  // "Norwegian",
  // "Persian",
  // "Polish",
  // "Portuguese",
  // "Romanian",
  // "Russian",
  // "Serbian",
  // "Slovak",
  // "Slovenian",
  // "Spanish",
  // "Swahili",
  // "Swedish",
  // "Tagalog",
  // "Tamil",
  // "Thai",
  // "Turkish",
  // "Ukrainian",
  // "Urdu",
  // "Vietnamese",
  // "Welsh",
]