FROM node:18-alpine

# Pass the environment variables to the build command
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG AUTHOR_URL
ARG AUTHOR_TOKEN
ARG APP_ENV
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_OPENAI_URL
ARG NEXT_PUBLIC_OPENAI_API_KEY
ARG OPENAI_URL
ARG OPENAI_API_KEY

# Set the environment variables for the build process
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV AUTHOR_URL=$AUTHOR_URL
ENV AUTHOR_TOKEN=$AUTHOR_TOKEN
ENV APP_ENV=$APP_ENV
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER=$FIREBASE_MESSAGING_SENDER
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
ENV NEXT_PUBLIC_OPENAI_URL=$NEXT_PUBLIC_OPENAI_URL
ENV NEXT_PUBLIC_OPENAI_API_KEY=$NEXT_PUBLIC_OPENAI_API_KEY

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install project dependencies
RUN yarn

# Copy the entire project directory to the container
COPY . .

# Build the Next.js app for production
RUN yarn build

# Expose the desired port (default is 3000 for Next.js)
EXPOSE 3000

# Start the Next.js app
CMD ["yarn", "start"]