name: Build Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/canvas:latest
          build-args: |
            NEXT_PUBLIC_BASE_URL=${{ secrets.DOCKERHUB_USERNAME }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.DOCKERHUB_USERNAME }}
            AUTHOR_URL=${{ secrets.DOCKERHUB_USERNAME }}
            AUTHOR_TOKEN=${{ secrets.DOCKERHUB_USERNAME }}
            APP_ENV=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_API_KEY=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_AUTH_DOMAIN=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_PROJECT_ID=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_MESSAGING_SENDER=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_APP_ID=${{ secrets.DOCKERHUB_USERNAME }}
            FIREBASE_MEASUREMENT_ID=${{ secrets.DOCKERHUB_USERNAME }}
            NEXT_PUBLIC_OPENAI_URL=${{ secrets.DOCKERHUB_USERNAME }}
            NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.DOCKERHUB_USERNAME }}
            OPENAI_URL=${{ secrets.DOCKERHUB_USERNAME }}
            OPENAI_API_KEY=${{ secrets.DOCKERHUB_USERNAME }}


