name: Build Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build production Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/canvas:latest
          build-args: |
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            AUTHOR_URL=${{ secrets.AUTHOR_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            APP_ENV=${{ secrets.APP_ENV }}
            FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            FIREBASE_MESSAGING_SENDER=${{ secrets.FIREBASE_MESSAGING_SENDER }}
            FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
            OPENAI_URL=${{ secrets.OPENAI_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_KEY_PREMIUM=${{ secrets.OPENAI_API_KEY_PREMIUM }}
            DOKU_URL=${{ secrets.DOKU_URL }}
            DOKU_CLIENT_ID=${{ secrets.DOKU_CLIENT_ID }}
            DOKU_SECRET_KEY=${{ secrets.DOKU_SECRET_KEY }}

      - name: Build staging Docker image
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/canvas:develop
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://stage.languageai.world/
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            AUTHOR_URL=${{ secrets.AUTHOR_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            APP_ENV=${{ secrets.APP_ENV }}
            FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            FIREBASE_MESSAGING_SENDER=${{ secrets.FIREBASE_MESSAGING_SENDER }}
            FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
            OPENAI_URL=${{ secrets.OPENAI_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_KEY_PREMIUM=${{ secrets.OPENAI_API_KEY_PREMIUM }}
            DOKU_URL=${{ secrets.DOKU_URL }}
            DOKU_CLIENT_ID=${{ secrets.DOKU_CLIENT_ID }}
            DOKU_SECRET_KEY=${{ secrets.DOKU_SECRET_KEY }}
