name: Pull request Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Pull Request Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/canvas:pull
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://stage.languageai.world/
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            AUTHOR_URL=${{ secrets.AUTHOR_URL }}
            APP_ENV=${{ secrets.APP_ENV }}
            FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            FIREBASE_MESSAGING_SENDER=${{ secrets.FIREBASE_MESSAGING_SENDER }}
            FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
            OPENAI_URL=${{ secrets.OPENAI_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_KEY_PREMIUM=${{ secrets.OPENAI_API_KEY_PREMIUM }}
            DOKU_URL=${{ secrets.DOKU_URL }}
            DOKU_CLIENT_ID=${{ secrets.DOKU_CLIENT_ID }}
            DOKU_SECRET_KEY=${{ secrets.DOKU_SECRET_KEY }}
            DATOCMS_GRAPHQL_URL=${{ secrets.DATOCMS_GRAPHQL_URL }}
            DATOCMS_TOKEN=${{ secrets.DATOCMS_TOKEN }}
